Repository cri-o/containrs, pull requests merged in 2020-10, with the labels that each got.

#95 Add generated proto sources to repo
  build.rs
  src/criapi.rs
  src/criapi/mod.rs
  src/criapi/runtime.v1alpha2.rs
  tests/common.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#107 Add capabilities module
  src/capability.rs
  src/config.rs
  src/lib.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#108 Add log_directory to sandbox data
  src/runtime_service/run_pod_sandbox.rs
  src/sandbox/mod.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#106 Add seccomp handling
  src/capability.rs
  src/lib.rs
  src/oci_spec/runtime.rs
  src/seccomp.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#84 Add CNI config and plugin initialization
  Cargo.lock
  Cargo.toml
  src/error.rs
  src/lib.rs
  src/main.rs
  src/network/cni.rs
  src/network/cni/config.rs
  src/network/cni/exec.rs
  src/network/cni/mod.rs
  src/network/mod.rs
  src/server.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#117 Replace 'extern crate' with bitflags macro import
  src/lib.rs
  src/sandbox/mod.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#118 Add annotations to sandbox data
  src/runtime_service/run_pod_sandbox.rs
  src/sandbox/mod.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#111 Add CNI config integration tests
  .github/workflows/ci.yml
  Makefile
  src/network/cni/mod.rs
  tests/cni/99-loopback.conf
  tests/common.rs
  tests/integration_tests/cni.rs
  tests/integration_tests/mod.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#130 Allow capabilities to be parsed with and without CAP_ prefix
  src/capability.rs
  src/seccomp.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#133 Publish API docs on gh-pages branch
  .github/workflows/gh-pages.yml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#132 Move Config into Server module
  Cargo.toml
  src/bin/criserver.rs
  src/lib.rs
  src/server/config.rs
  src/server/mod.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#141 Fix gh-pages publishing and add badge to README.md
  .github/workflows/gh-pages.yml
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#142 Deflake integration tests
  tests/common.rs
  tests/integration_tests/cni.rs
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#121 Make CNI network add/del work
  Cargo.lock
  Cargo.toml
  src/network/cni/config.rs
  src/network/cni/exec.rs
  src/network/cni/mod.rs
  src/network/cni/namespace.rs
  src/network/cni/netlink.rs
  src/network/cni/plugin.rs
  src/network/mod.rs
  src/sandbox/mod.rs
  src/server/config.rs
  src/server/mod.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#152 Make cri module private again
  src/kubernetes/mod.rs
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none

#151 Fix server shutdown integration test flake
  .github/workflows/ci.yml
  Makefile
  src/kubernetes/server/mod.rs
  tests/common.rs
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#154 Use ToString::to_string over |x| x.to_string()
  src/error.rs
  src/seccomp.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#155 Use Status transformer traits for easier error mapping
  src/kubernetes/cri/cri_service.rs
  src/kubernetes/cri/runtime_service/run_pod_sandbox.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#161 Fix dependabot PR CI running twice
  .github/workflows/ci.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#171 Add foreign function interface via cbindgen
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  build.rs
  src/ffi/ffi.h
Labels: approved, dco-signoff: yes, kind/feature, release-note

#177 Add error handling support to FFI
  Cargo.lock
  Cargo.toml
  build.rs
  src/bin/criserver.rs
  src/error.rs
  src/ffi/error.rs
  src/ffi/ffi.h
  src/ffi/mod.rs
  src/ffi/network/mod.rs
  src/lib.rs
  src/network/cni/mod.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#176 Upload artifacts to GCS
  .github/workflows/ci.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#157 Add CNI network storage support
  Cargo.lock
  Cargo.toml
  src/kubernetes/cri/cri_service.rs
  src/kubernetes/server/mod.rs
  src/network/cni/config.rs
  src/network/cni/mod.rs
  src/network/mod.rs
  src/storage/default_key_value_storage.rs
  src/storage/mod.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#143 Add first OCI runtime abstraction
  src/lib.rs
  src/oci/container/local.rs
  src/oci/container/mod.rs
  src/oci/mod.rs
  src/oci/spec/mod.rs
  src/oci/spec/runtime.rs
  src/seccomp.rs
Labels: approved, dco-signoff: yes, kind/design, lgtm, release-note-none
