Repository cri-o/containrs, pull requests merged in 2020-09, with the labels that each got.

#2 Add stubs for container messages
  src/server.rs
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#7 Remove duplicate build.rs file
  src/build.rs
Labels: dco-signoff: yes, release-note-none

#10 Use anyhow crate for error handling
  Cargo.lock
  Cargo.toml
  build.rs
Labels: dco-signoff: yes, release-note-none

#12 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dco-signoff: yes, release-note-none

#13 Add Makefile for running common targets
  Makefile
Labels: dco-signoff: yes, release-note-none

#14 Add Cargo.toml meta data
  Cargo.toml
  LICENSE
Labels: dco-signoff: yes, lgtm, release-note-none

#11 Split-up lib and bin inside crate
  Cargo.toml
  src/criapi.rs
  src/lib.rs
  src/main.rs
  src/runtime.rs
  src/server.rs
Labels: dco-signoff: yes, release-note-none

#19 Add *.orig to .gitignore
  .gitignore
Labels: dco-signoff: yes, kind/cleanup, release-note-none

#17 Add OWNERS file
  OWNERS
Labels: dco-signoff: yes, kind/documentation, release-note-none

#18 Add GitHub actions
  .github/workflows/ci.yml
  .rustfmt.toml
  Cargo.lock
  Cargo.toml
  src/runtime.rs
  tests/e2e.rs
  tests/integration.rs
Labels: approved, dco-signoff: yes, kind/design, lgtm, release-note-none

#24 Add deny-missing-docs macro
  src/lib.rs
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#23 Split runtime and image service in different modules
  src/image_service.rs
  src/lib.rs
  src/runtime_service.rs
  src/server.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#21 Listen on unix domain socket
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/lib.rs
  src/server.rs
  src/unix_stream.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#31 Fix rustfmt lint
  src/server.rs
  src/unix_stream.rs
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#40 Add context to socket dir creation error
  src/server.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#33 Add GRPC interceptor to debug log requests
  src/runtime_service.rs
  src/server.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#41 Use `with_context` to rely on lazy evaluation
  src/server.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#42 Add code coverage report
  .codecov.yml
  .github/workflows/ci.yml
  .rustfmt.toml
  README.md
  src/server.rs
Labels: approved, dco-signoff: yes, kind/design, lgtm, release-note-none

#32 Add first sandbox abstraction
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/runtime_service.rs
  src/sandbox/mod.rs
  src/sandbox/pinned.rs
Labels: approved, dco-signoff: yes, kind/design, lgtm, release-note-none

#45 Add ready method for Pod
  src/sandbox/mod.rs
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note

#46 Enhance sandbox ready() docs
  src/sandbox/mod.rs
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#38 Add first integration test
  Cargo.lock
  Cargo.toml
  Makefile
  src/config.rs
  src/server.rs
  tests/common.rs
  tests/integration.rs
Labels: approved, dco-signoff: yes, kind/design, lgtm, release-note-none

#44 Split-up RPCs into dedicated modules
  src/image_service.rs
  src/image_service/image_fs_info.rs
  src/image_service/image_status.rs
  src/image_service/list_images.rs
  src/image_service/mod.rs
  src/image_service/pull_image.rs
  src/image_service/remove_image.rs
  src/runtime_service.rs
  src/runtime_service/attach.rs
  src/runtime_service/container_stats.rs
  src/runtime_service/container_status.rs
  src/runtime_service/create_container.rs
  src/runtime_service/exec.rs
  src/runtime_service/exec_sync.rs
  src/runtime_service/list_container_stats.rs
  src/runtime_service/list_containers.rs
  src/runtime_service/list_pod_sandbox.rs
  src/runtime_service/mod.rs
  src/runtime_service/pod_sandbox_status.rs
  src/runtime_service/port_forward.rs
  src/runtime_service/remove_container.rs
  src/runtime_service/remove_pod_sandbox.rs
  src/runtime_service/reopen_container_log.rs
  src/runtime_service/run_pod_sandbox.rs
  src/runtime_service/start_container.rs
  src/runtime_service/status.rs
  src/runtime_service/stop_container.rs
  src/runtime_service/stop_pod_sandbox.rs
  src/runtime_service/update_container_resources.rs
  src/runtime_service/update_runtime_config.rs
  src/runtime_service/version.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#49 Add OCI runtime spec
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/oci_spec/mod.rs
  src/oci_spec/runtime.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#50 Add run_pod_sandbox integration test
  tests/integration.rs
  tests/integration_tests/mod.rs
  tests/integration_tests/run_pod_sandbox.rs
  tests/integration_tests/version.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#53 Optimize release build with lto and strip it
  Cargo.toml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#54 Derive builder for Config
  src/config.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#55 Handle server termination by signal
  Cargo.lock
  Cargo.toml
  src/server.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#51 Add GitHub actions badge
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none

#66 Fix proto package name
  proto/criapi.proto
  src/criapi.rs
  tests/common.rs
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none

#64 Remove unwrap in pod sandbox test
  src/runtime_service/run_pod_sandbox.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#62 Add tests to socket path creation
  src/server.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#65 Add --log-scope for logging all crates
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/server.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#63 Make socket path work in rootless mode
  Cargo.lock
  Cargo.toml
  src/config.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#70 Add static binary build to GitHub action
  .github/workflows/ci.yml
  Makefile
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#47 Add first storage implementation
  Cargo.lock
  Cargo.toml
  Makefile
  src/config.rs
  src/cri_service.rs
  src/image_service/image_fs_info.rs
  src/image_service/image_status.rs
  src/image_service/list_images.rs
  src/image_service/mod.rs
  src/image_service/pull_image.rs
  src/image_service/remove_image.rs
  src/lib.rs
  src/runtime_service/attach.rs
  src/runtime_service/container_stats.rs
  src/runtime_service/container_status.rs
  src/runtime_service/create_container.rs
  src/runtime_service/exec.rs
  src/runtime_service/exec_sync.rs
  src/runtime_service/list_container_stats.rs
  src/runtime_service/list_containers.rs
  src/runtime_service/list_pod_sandbox.rs
  src/runtime_service/mod.rs
  src/runtime_service/pod_sandbox_status.rs
  src/runtime_service/port_forward.rs
  src/runtime_service/remove_container.rs
  src/runtime_service/remove_pod_sandbox.rs
  src/runtime_service/reopen_container_log.rs
  src/runtime_service/run_pod_sandbox.rs
  src/runtime_service/start_container.rs
  src/runtime_service/status.rs
  src/runtime_service/stop_container.rs
  src/runtime_service/stop_pod_sandbox.rs
  src/runtime_service/update_container_resources.rs
  src/runtime_service/update_runtime_config.rs
  src/runtime_service/version.rs
  src/server.rs
  src/storage/default_key_value_storage.rs
  src/storage/mod.rs
  tests/common.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#78 Improve error messages so as to indicate failures
  src/storage/default_key_value_storage.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#75 Print log file and line when running with debug/trace level
  src/server.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#73 Add basic network abstraction
  src/config.rs
  src/lib.rs
  src/network/cni.rs
  src/network/mod.rs
  src/sandbox/mod.rs
  src/server.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#74 Manually debug log each request and response
  src/cri_service.rs
  src/image_service/mod.rs
  src/runtime_service/mod.rs
  src/server.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#82 Fix clippy lints
  src/server.rs
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, release-note-none

#91 Improve error messages so as to indicate failures
  src/server.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#86 Add linux namespaces to sandbox data
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/runtime_service/run_pod_sandbox.rs
  src/sandbox/mod.rs
  tests/integration_tests/run_pod_sandbox.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note

#93 Add hostname to sandbox data
  src/runtime_service/run_pod_sandbox.rs
  src/sandbox/mod.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none

#96 Add server status RPC implementation
  src/runtime_service/status.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none
