Repository cri-o/containrs, pull requests merged in 2020-11, with the labels that each got.

#240 fixed lint issues
  src/sandbox/mod.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none

#219 Rename project to containrs
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  src/bin/server.rs
  tests/common.rs
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note

#235 init oci runtime
  src/oci/mod.rs
  src/oci/oci_runtime.rs
Labels: approved, dco-signoff: yes, kind/feature, lgtm, release-note-none
